### ISSUE TITLE
Supports different packaging formats for different platforms

### ISSUE THREAD

**Issue by seanly** [LinuxSuRen/http-downloader#137]
`tar: true`:  the default is tar.gz, but some software is zip for Windows; `tar: false` is binary format.

for exmaple: 
```
tar: false 
or
formatOverrides:
  windows: binary # zip/tar.gz
  linux: zip

```

**Comment by amoghrajesh** [comment]
@seanly I don't completely understand what is to be done as a part of this issue but I would like to attempt it if it can be explained better. Can you also give me some pointers on where to start and which code to look for?

**Comment by LinuxSuRen** [comment]
hi @amoghrajesh , thanks for reaching out to us. As you may know, this project aims to make it be easier to download or install an executable binary file from GitHub release assets. But there is a problem which is related to the different platforms.

Let me give you an example. For this project, the asset file name is `hd-windows-amd64.zip` in windows, but the suffix is `tar.gz` in linux.

This is a sample config:

```yaml
filename: "hd-{{.OS}}-{{.Arch}}.tar.gz"
binary: hd
```

It's incorrect for the windows platform. So @seanly might want to offer a potential solution to fix it. Add the following configuration support like below:

```yaml
filename: "hd-{{.OS}}-{{.Arch}}"
binary: hd
formatOverrides:
  windows: zip
  linux: tar.gz
```

## Deep reading
This command will fetch [hd-home](https://github.com/LinuxSuRen/hd-home) first, then [parse](https://github.com/LinuxSuRen/http-downloader/blob/538372e964a724b165d2dc74ddbc7095217e3d42/cmd/get.go#L125) the configuration.

## References
* https://github.com/LinuxSuRen/hd-home/blob/master/config/linuxsuren/http-downloader.yml
* https://github.com/LinuxSuRen/http-downloader/releases/tag/v0.0.42
* https://github.com/LinuxSuRen/http-downloader/blob/538372e964a724b165d2dc74ddbc7095217e3d42/pkg/installer/types.go#L4

**Comment by amoghrajesh** [comment]
@LinuxSuRen I am interested in working on this issue but I want a little more context on this. 
A few doubts from me:

1. Will the code changes be in https://github.com/LinuxSuRen/http-downloader or https://github.com/LinuxSuRen/hd-home repo?
2. The url is constructed somewhere in the code which is using the old config. Now we want to make it use the right one through things like formatOverrides. Am I getting it right?

**Comment by LinuxSuRen** [comment]
hi @amoghrajesh 

1. [hd-home](https://github.com/LinuxSuRen/hd-home) is a config repo. [http-downloader](https://github.com/LinuxSuRen/http-downloader) is the repo for the command line. So, we need to change the code from [http-downloader](https://github.com/LinuxSuRen/http-downloader)
2. You got the point. But one more thing that we need to consider. Make sure no compatible issue happens.

**Comment by amoghrajesh** [comment]
Hi @LinuxSuRen I have understood the issue conceptually and have created PRs in the respective repositories to fix this.
In the hd-home repo: https://github.com/LinuxSuRen/hd-home/pull/68
In the hd-downloader repo: https://github.com/LinuxSuRen/http-downloader/pull/150.

I wanted to know a simple way this can be tested for sanity before a merge. How do I do that?

**Comment by LinuxSuRen** [comment]
Thanks for your quick action. The test steps are simple.

* Compile this project with command: `make`
* Clone the repo https://github.com/amoghrajesh/hd-home into directory `~/.config/hd-home`, change it to branch `amogh-patch`
* Test this feature with command `./bin/hd install linuxsuren/http-downloader --fetch=false`
  * The key point is about the flag `--fetch`, it would clone `hd-home` again.

It would be great if you have Windows and Linux platforms to test it. [Virtualbox](https://www.virtualbox.org/) can help you to have a Windows if you don't have one.

An example of local directory hd-home:
```shell
~/.config/hd-home
➜  hd-home git:(master) ls -hal
total 56
drwxr-xr-x  13 rick  staff   416B Sep  3 14:00 .
drwxr-x--x  18 rick  staff   576B May  7 18:57 ..
drwxr-xr-x   5 rick  staff   160B Sep  3 14:00 .devcontainer
drwxr-xr-x  11 rick  staff   352B Oct  2 07:25 .git
drwxr-xr-x   4 rick  staff   128B May  7 18:57 .github
-rw-r--r--   1 rick  staff     7B May  7 18:57 .gitignore
-rw-r--r--   1 rick  staff   179B Jun 27 22:54 .gitpod.Dockerfile
-rw-r--r--   1 rick  staff    34B Jun 27 22:54 .gitpod.yml
-rw-r--r--   1 rick  staff   1.0K May  7 18:57 LICENSE
-rw-r--r--   1 rick  staff    55B Sep  3 14:00 Makefile
-rw-r--r--   1 rick  staff    28B May  7 18:57 OWNERS
-rw-r--r--   1 rick  staff   1.3K Jun 27 22:54 README.md
drwxr-xr-x  34 rick  staff   1.1K Sep 29 09:29 config
```

**Comment by amoghrajesh** [comment]
@LinuxSuRen I have handled these tasks in the PRs attached. Please have a look and review it. Thanks!
