### ISSUE TITLE
Request to support for getting latest version by accessing a URL

### ISSUE THREAD

**Issue by JohnNiang** [LinuxSuRen/http-downloader#163]
> You did an excellent job. But normally, users don't need to provide the version. For this case, users cannot get any tips when the command occurs errors. So, I prefer to let [hd](https://gitee.com/linuxsuren/http-downloader) be able to get the latest version by access a URL.
>  
> _Originally posted by @LinuxSuRen in https://github.com/LinuxSuRen/hd-home/issues/90#issuecomment-939472872_

Please see also: https://github.com/LinuxSuRen/hd-home/pull/90#issuecomment-939472182.

Some binaries are hosted by other platform instead of GitHub, like this form below:

```bash
curl -LO https://storage.googleapis.com/spinnaker-artifacts/spin/$(curl -s https://storage.googleapis.com/spinnaker-artifacts/spin/latest)/linux/amd64/spin
```

We cannot determine the latest release of [spin](https://github.com/spinnaker/spin) project only by GitHub API. Instead, we can request towards `https://storage.googleapis.com/spinnaker-artifacts/spin/latest` to obtain the latest version.

So we should provide another [field](https://github.com/LinuxSuRen/hd-home#fields), such as `latestURL`, to change the default behaviour, fetching latest version from GitHub latest release.

**Comment by LinuxSuRen** [comment]
How about providing a field `latestVersion` into the following struct

https://github.com/LinuxSuRen/http-downloader/blob/b2f36765c8458f3b12ff8154c458c0c95fd7d12e/pkg/installer/types.go#L10

this field could support different formats:
* empty, get the latest version from GitHub release
* a URL, try to send a GET request and get the version from the response
* other cases
