### ISSUE TITLE
Speed up cloning by setting depth option of git clone

### ISSUE THREAD

**Issue by JohnNiang** [LinuxSuRen/http-downloader#52]
Maybe we could speed up clone speed cloning by setting `depth` option of git clone, especially more and more `hd-home` commits.

```diff
- git clone https://github.com/LinuxSuRen/hd-home ${configDir}.
+ git clone --depth 1 https://github.com/LinuxSuRen/hd-home ${configDir}.
```

> https://github.com/LinuxSuRen/http-downloader/blob/3cbc1264d2590358c49da15bb6818002dc7bbe14/cmd/fetch.go#L43

**Comment by LinuxSuRen** [comment]
Sure, please go ahead if you want to help on this.

**Comment by JohnNiang** [comment]
I found that the preceding `pathExists` check would need full cloning `hd-home` repo.

**Comment by LinuxSuRen** [comment]
Or, we can offer an option to using an alternative git repository. So if it's too slow for some users, they can mirror it to another repo as an backup repo.
